server:
  port: 8889
  
spring: 
  application:
    name: empresa
  data:
    mongodb:
      database: challenge
      host: 172.18.0.1
      #host: localhost
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8761/eureka/}
  
  