server:
  port: 8889
  
spring: 
  application:
    name: empresa
  data:
    mongodb:
      database: challenge
      host: 172.18.0.1
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
  