version: '3'

services:
 mongodb:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - /var/data
      
 discovery:
    build:
      context: ./app_back_discovery
      dockerfile: Dockerfile
    image: discovery-server-image
    ports:
      - 8761:8761
      
 gateway:
    build:
      context: ./app_back_gateway
      dockerfile: Dockerfile
    image: gateway-server-image
    ports:
      - 8762:8762
    depends_on: 
      - discovery
 
 auth:
    build:
      context: ./app_back_auth
      dockerfile: Dockerfile
    image: auth-server-image
    ports:
      - 8888:8888
    depends_on: 
      - discovery
 
 empresa:
    build:
      context: ./app_back_empresa
      dockerfile: Dockerfile
    image: empresa-server-image
    ports:
      - 8889:8889
    depends_on: 
      - mongodb
      - discovery      
 
 reclamacao:
    build:
      context: ./app_back_reclamacao
      dockerfile: Dockerfile
    image: reclamacao-server-image
    ports:
      - 9090:9090
    depends_on: 
      - mongodb
      - discovery

  