server:
  port: 8888
 
spring:
   application:
    name: auth 

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery:8761/eureka/}
  instance:
     preferIpAddress:true 

