server:
  port: ${PORT:8080}
  
logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
         
zuul:
 sensitive-headers:
  
          