server:
  port: 9090
  
spring:
  application:
    name: reclamacao
  data:
    mongodb:
      database: challenge
      host: 172.18.0.1
      port: 27017
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
         
   